// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzk-9N35qWuyabKK6w2dknPyKeDA0vNsw',
    appId: '1:926300556774:web:fc97e0eff891a70b221a27',
    messagingSenderId: '926300556774',
    projectId: 'basiccrudfirebseflutter',
    authDomain: 'basiccrudfirebseflutter.firebaseapp.com',
    storageBucket: 'basiccrudfirebseflutter.appspot.com',
    measurementId: 'G-WCP05J3FG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJzrFepyiclg8_GV6b9jCCjwsyRqPukic',
    appId: '1:926300556774:android:89b569a80e3e5aa6221a27',
    messagingSenderId: '926300556774',
    projectId: 'basiccrudfirebseflutter',
    storageBucket: 'basiccrudfirebseflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_oxEqfll0X5in43G5q8i57ZP2IHs7HnE',
    appId: '1:926300556774:ios:42b33f9940396612221a27',
    messagingSenderId: '926300556774',
    projectId: 'basiccrudfirebseflutter',
    storageBucket: 'basiccrudfirebseflutter.appspot.com',
    iosBundleId: 'com.example.basicff',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_oxEqfll0X5in43G5q8i57ZP2IHs7HnE',
    appId: '1:926300556774:ios:42b33f9940396612221a27',
    messagingSenderId: '926300556774',
    projectId: 'basiccrudfirebseflutter',
    storageBucket: 'basiccrudfirebseflutter.appspot.com',
    iosBundleId: 'com.example.basicff',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzk-9N35qWuyabKK6w2dknPyKeDA0vNsw',
    appId: '1:926300556774:web:b647551893154f24221a27',
    messagingSenderId: '926300556774',
    projectId: 'basiccrudfirebseflutter',
    authDomain: 'basiccrudfirebseflutter.firebaseapp.com',
    storageBucket: 'basiccrudfirebseflutter.appspot.com',
    measurementId: 'G-6MKGL1XY1N',
  );

}